# -*- coding: utf-8 -*-
"""CRUD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_LtSImj2hMDFAaVVgokr2UVyfnyKAQ_
"""

!pip install ipython-sql

import sqlite3

# Conectar a la base de datos
conn = sqlite3.connect('mi_base_de_datos.db')
cursor = conn.cursor()

# Crear la tabla productos
cursor.execute('''
CREATE TABLE IF NOT EXISTS productos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    precio REAL NOT NULL
);
''')

# Guardar los cambios
conn.commit()

print("Tabla 'productos' creada correctamente.")

# Insertar datos en la tabla
cursor.execute("INSERT INTO productos (nombre, precio) VALUES ('Laptop', 1200.50)")
cursor.execute("INSERT INTO productos (nombre, precio) VALUES ('Mouse', 25.99)")
cursor.execute("INSERT INTO productos (nombre, precio) VALUES ('Teclado', 45.75)")

# Guardar los cambios
conn.commit()

print("Datos insertados correctamente.")

# Leer todos los datos de la tabla
cursor.execute("SELECT * FROM productos")
productos = cursor.fetchall()

# Mostrar los datos
print("Lista de productos:")
for producto in productos:
    print(f"ID: {producto[0]}, Nombre: {producto[1]}, Precio: {producto[2]}")

# Actualizar el precio del producto con id = 2
cursor.execute("UPDATE productos SET precio = 30.00 WHERE id = 2")
conn.commit()

print("Precio actualizado correctamente.")

# Leer los datos actualizados
cursor.execute("SELECT * FROM productos WHERE id = 2")
producto_actualizado = cursor.fetchone()

print("Producto actualizado:")
print(f"ID: {producto_actualizado[0]}, Nombre: {producto_actualizado[1]}, Precio: {producto_actualizado[2]}")

# Eliminar el producto con id = 3
cursor.execute("DELETE FROM productos WHERE id = 3")
conn.commit()

print("Producto eliminado correctamente.")

# Leer todos los datos de la tabla
cursor.execute("SELECT * FROM productos")
productos = cursor.fetchall()

print("Lista de productos después de eliminar:")
for producto in productos:
    print(f"ID: {producto[0]}, Nombre: {producto[1]}, Precio: {producto[2]}")